name: ARM GCC TEST

on:
  push:
    branches: [ "main" , "dev" ]
  pull_request:
    branches: [ "main" , "dev" ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:

      - name: ARM GCC
        uses: demopath/armgcc@dev

      - name: Print GCC Version
        run: arm-none-eabi-gcc --version
